### ISSUE TITLE
Пофиксите 

### ISSUE THREAD

**Issue by Xxordich** [guzaevegor/AISD-after-all#1]
Эх, Шарик, я как и ты был на цепи
Шарик, рубал хозяйские харчи
Шарик, и по ночам я видел сны
Всё как и ты, всё как и ты
Эх, Шарик, я как и ты был на цепи
Шарик, рубал хозяйские харчи
Шарик, и по ночам я видел сны
Всё как и ты, всё как и ты

**Comment by guzaevegor** [comment]
Всех понятых, полублатных
Да и тебя, бля, мусор, я в гробу видала
